src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui
This is the layout attempt to make display right on most setups.
On pictures below, in order, you have: before, after, and Win7 with Qt5
=> main page UI layout

Specifications/GEMS-file-specification.txt
Specification of GEMS formats deduced from manipulations I have made in Dosbox.
Verified on only 1 patch (the first). The operator order is a mess, it's a result I was able to observe by testing.
=> add reverse-engineered GEMS format specification

CMakeLists.txt, FMBankEdit.pro, Specifications/GEMS-file-specification.txt, src/FileFormats/ffmt_enums.h, src/FileFormats/ffmt_factory.cpp, src/FileFormats/format_gems_pat.cpp, src/FileFormats/format_gems_pat.h
I implement read support for BNK and PAT files.
It's to test, as some instruments are sounding good and some not so much.
The values shown in both editors seem matching for most.
- no support of "CH3" stuff
- no support of LFO on/frequency (which GEMS takes as per-instrument)
- no support of disabling Left/Right
- I took GEMS "SLevel" as "Sustain", and GEMS "Sustain" as "Decay2". Check it
- I'm not sure about interpretation of Detune (GEMS has -3..+3) ~~which I converted to 0..7 range adding 3~~ using raw values of file
- conversions of operator orders to verify...
- to implement "Disable" flag on operator I chose to override level with 127
=> GEMS file format support, experimental

CMakeLists.txt, FMBankEdit.pro, src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui, src/register_editor.cpp, src/register_editor.h, src/register_editor.ui, src/translations/opn2bankeditor_fr_FR.ts
Adds a register editor as dialog.
This allows to edit by hand and also copy-paste into a form of line edits which are chained.
It will remove all crap like '$' and ',' so it can take the bytes from various hex dumps and asm files.
=> add basic register editor

src/audio.cpp, src/bank_editor.h
It's a fix for #32 
This keeps track of a set of keys pressed on keyboard.
Then it can filter out the release events which don't match a previous key-press.
It's expected occurrence that there will happen pairs of unmatched press/release.
(example: text edit consumes a key press for itself, doesn't care about key release and lets it through)
=> ignore unmatched key release events on keyboard

src/bank_editor.cpp, src/bank_editor.h
#42
Permits a copy between two different processes.
The clipboard has a binary content and mime type identifier.
=> instrument copy in the global clipboard

src/bank.cpp, src/bank.h, src/importer.cpp
#45 
This is to fix the copy problem when the banks don't exist or mismatch by their index in the table.
Based on the PR #47
I have tried to break this down to make it more clear for me, by the naming of variables.
I did a few checks, but please test yourself to check behavior as conformant to before.
=> Fix importer

src/importer.cpp, src/importer.ui, src/translations/opn2bankeditor_fr_FR.ts
This adds a selection to choose where the instruments go in "assoc" mode.
FR translation is provided, RU will beed to update.
A changed text fixes a mistake in the status bar text.
I've spent another "good" time (:stuck_out_tongue:) in Qt designer to lay this out while ensuring it's the left part which stretches when resizing the dialog.
To do this I have broken the big grid layout in smaller ones.
I'm guessing it will be possible to copy this change directly to the other editor. This will be very helpful.
=> importer: add the choice of import target

CMakeLists.txt
Like OPL3, fixes the plot data which is not computed by lack of `ENABLE_PLOTS` definitions.
=> fix the compile time definition of ENABLE_PLOTS

src/bank_editor.cpp, src/bank_editor.h, src/controlls.cpp
Same as OPL3BankEditor, except one important thing:
At startup it's now needed to set the backup like OPL3 does.
(or it will popup the dialog of unsaved changes on "Open" at startup)
At the same place I reciprocated how it syncs the global parameters of banks on OPL3 startup.
(was deep tremolo/vibrato, here LFO settings)
```
m_bank.lfo_enabled = ui->lfoEnable->isChecked();
m_bank.lfo_frequency = ui->lfoFrequency->currentIndex();
m_bankBackup = m_bank;
```
=> display blank entries in gray color

Specifications/WOPN-and-OPNI-Specification-draft.txt
:warning: incomplete and sent for review
List of what's changed this far, and motivation for changing.
- data of large size was pushed at the back of file, so it can be permitted to easily truncate, and the small and large data don't interleave
- at the back of file is a string segment and data segment. the usual file parts are going to refer into data segment by 32-bit index and size; the string part is going to be refered by only index and the UTF-8 string will run until either the '\0' or segment end.
- add the Sample chunk in replacement of PCM. Loop specification is out, as being part of SFZ, and are added channel count and tag for data type, such that other data than PCM may be given, hence the rename. It's not a thing at present, but flac or opus is a possibility.
The Sample chunk …
=> WIP wopn file draft

CMakeLists.txt, FMBankEdit.pro, src/FileFormats/ffmt_enums.h, src/FileFormats/ffmt_factory.cpp, src/FileFormats/format_saxman_ymx.cpp, src/FileFormats/format_saxman_ymx.h
It's the revision 0 of format which has existing banks in, not revision 1 specified on sega retro.
Sources are found in Sonic ROM editing tools.
Instrument payload is formatted as SMPS. https://segaretro.org/SCHG:SMPS_Hacking/Voices_and_Samples
It's as usual data formats except operator's fields were interleaved.
Some instruments sound good ~and some are crap~ (FIXED), test it.
=> add YMX format loader

src/ins_names.h
This arranges the bitfield to fit in the 32 bit integer, even in ms-bitfields configuration
attempt at bug #63
=> compatible bit-packing under Windows

src/FileFormats/format_vgm_import.cpp, src/FileFormats/ym2612_to_wopi.hpp
#71 
Backported instrument sharing from OPL chip simulator.
I found this set of VGM having YM2608 opcodes.
[vgms.zip](https://github.com/Wohlstand/OPN2BankEditor/files/3014914/vgms.zip)
=> support YM2608 VGM

src/FileFormats/format_vgm_import.cpp
With vgz being merged, it has also merged a VGM fix.
However this fix can disrupt the way how data stream is read when the data offset is misinterpreted, because the second fix was not part of the branch.
It means that files which were working before (by chance) can maybe no longer work.
(happened to me on OPL-BE side)
It's the fix found in YM2151 branch by itself, which is recommendable to pick.
=> fixed offset problem of the vgm file reader

src/FileFormats/format_bamboo_bti.cpp
#71
BTI update to specification 1.2.0
Nothing is to add, beside the version check.
Since the size is filled inside file structures, the new data content will be just skipped, and it's nothing of interest to the bank editor.
About BTM (module) it takes more work than to go fish the BTI data structure inside the file, because it's differently organized. I think, if I'm not mistaken, various chunks are arranged at separated places in the files, so it needs a bit different parsing.
=> bti: update for specification 1.2.0

CMakeLists.txt, FMBankEdit.pro, src/FileFormats/text_format.cpp, src/FileFormats/text_format.h, src/FileFormats/text_format_tokens.cpp, src/FileFormats/text_format_tokens.h, src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui, src/metaparameter.h
#81
Hi, this shows a concept of using custom text formats for reading and writing.
It's not implemented yet in the editor, and only has VOPM as a format now.
In `createVopmFormat`, it can be seen how to build a grammar for a format.
The `Val`s are to replace with the actual values of the instrument. To associate with values, it relies on MetaParameter, which has been given a setter function.
The `Int`s are just number fields which are ignored, and have defaults used for writing.
While writing, the whitespace tokens are used for human-readable formatting.
During parsing, the whitespace tokens are always ignored.
=> Importing and exporting with custom text formats

src/FileFormats/text_format.cpp, src/FileFormats/text_format.h, src/bank_editor.cpp
#71 @papiezak
This adds a special kind of format known as composite, which tries a sequence of different subformats until one will match.
As documented, PMD has two subformats. First, I will try the OPM, and second the OPN if that fails.
OPM instruments cannot interpret as OPN, which is not the case of the opposite.
https://pigu-a.github.io/pmddocs/pmdmml.htm#3-1
The commit defines PMD as a composite format.
=> Support PMD instrument type 2

src/FileFormats/text_format.cpp, src/FileFormats/text_format.h
add mml2vgm instrument format support
mml2vgm is the most active compiler for mml to MD/GEN's .vgm format.
=> add mml2vgm support

src/FileFormats/ffmt_enums.h, src/FileFormats/ffmt_factory.cpp, src/FileFormats/ffmt_factory.h, src/FileFormats/format_m2v_gyb.cpp, src/FileFormats/format_saxman_ymx.cpp, src/FileFormats/format_wohlstand_opn2.cpp, src/bank_editor.cpp
A backport of some capabilities from OPL3 Bank Editor.
The flags were set on file formats where appropriate.
=> Add GM-only and Needs-measure format capabilities

src/bank_editor.ui, src/operator_editor.ui
Fixes #39, rate scale level definition was taken from BambooTracker. Also, corrects some other texts which were leftovers from OPL3 Bank Editor and didn't matter when referring to OPN.
=> Editor texts improved

src/FileFormats/text_format.cpp
context: https://github.com/Wohlstand/OPN2BankEditor/issues/81 / https://github.com/Wohlstand/OPN2BankEditor/pull/82
In FMP distribution from 199x, there was a default template bank
definition file (`88NEIRO.TPI`) whose format was like this:
```
"Harpsichord
'@ 0
AR DR SR RR SL TL KS ML DT
'@ 31,12, 4,10, 1,32, 0,12, 0
'@ 31, 2, 4, 6,15,57, 3,15, 1
'@ 31,12, 4, 6, 0,30, 0, 1, 0
'@ 31, 5, 7, 7, 2, 0, 2, 3, 4
'@ 2,7
```
On the other hand, this is what we see from "Copy to FMP":
```
'@ FA 0
'@   0,  0,  0,  0,  0,  0,  0,  0,  0,   0
'@   0,  0,  0,  0,  0,  0,  0,  0,  0,   0
'@   0,  0,  0,  0,  0,  0,  0,  0,  0,   0
'@   0,  0,  0,  0,  0,  0,  0,  0,  0,   0
'@   0,  0
```
There are some notable differences, but so far what I find annoying is
that the last parameter (AM/DT2) was …
=> TextFormat: support FMP4 format as well as existing FMP7 format
